IAUECProfessorsEvaluation.Web/Models/Professor.cs
using AutoMapper;
using IAUECProfessorsEvaluation.Service.IService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IAUECProfessorsEvaluation.Web.Models
{
    public class Professor : Person
    {
        public int? ProfessorCode { get; set; }
        public int? Status { get; set; }


        public virtual ICollection<EducationalClass> EducationalClasses { get; set; }
        public virtual ICollection<ProfessorScore> ProfessorScores { get; set; }

        public int? ScientificRank { get; set; }
        public int? TeachingExperience { get; set; }
        public int? AcademicDegree { get; set; }
        public int? EducationPlaceUniversityRank { get; set; }
        public int? UniversityStudyPlace { get; set; }
        public int? UniversityWorkPlace { get; set; }
        public int? InPersonSession { get; set; }
        public int? OnlineSession { get; set; }
        public int? OthersSession { get; set; }
        public string Description { get; set; }
        public int? EntryAndExitStatus { get; set; }
        public int? ScoresAnnounceTimely { get; set; }
        public int? ExamQuestionsProvideTimely { get; set; }
        public int? ProfessorAccessStatus { get; set; }
        public int? GroupMangerComments { get; set; }
        public int? DeputyComments { get; set; }
        public int? AverageGradeEvaluation { get; set; }
        public Term Term { get; set; }

        public int CollegeRate { get; set; }
        
        public virtual int TotalScores {
            get
            {
                return (int)this.ProfessorScores.Sum(s => s.CurrentScore);
            }
        }
        public virtual int RankInUniversity
        {
            get;set;//return Mapper.Map<List<Model.Models.Professor>, List<Models.Professor>>(_professorService.GetAll().ToList()).IndexOf(professor);
        }
    }
}

IAUECProfessorsEvaluation.Web/Controllers/ProfessorController.cs
using AutoMapper;
using IAUECProfessorsEvaluation.Data.ReportModel;
using IAUECProfessorsEvaluation.Service.IService;
using IAUECProfessorsEvaluation.Service.Service;
using IAUECProfessorsEvaluation.Core.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IAUECProfessorsEvaluation.Model.Models;

namespace IAUECProfessorsEvaluation.Web.Controllers
{
    public class ProfessorController : Controller
    {
        private IProfessorService _professorService;
        private IProfessorScoreService _professorScoreService;
        private IEducationalGroupService _educationalGroupService;
        private ICollegeService _collegeService;
        private ITermService _termService;
        private IIndicatorService _indicatorService;
        private IRoleAccessService _roleAccessService;
        private IUserRoleService _userRoleService;
        private DapperService _reportService;
        private ILogService _logService;
        private IEducationalClassService _educationalClassService;

        public ProfessorController(
            IProfessorService professorService
            , IProfessorScoreService professorScoreService
            , IEducationalGroupService educationalGroupService
            , ICollegeService collegeService
            , ITermService termService
            , IIndicatorService indicatorService
            , IRoleAccessService roleAccessService
            , IUserRoleService userRoleService
            , ILogService logService
            , IEducationalClassService educationalClassService
            )
        {
            _professorService = professorService;
            _professorScoreService = professorScoreService;
            _educationalGroupService = educationalGroupService;
            _collegeService = collegeService;
            _termService = termService;
            _indicatorService = indicatorService;
            _roleAccessService = roleAccessService;
            _userRoleService = userRoleService;
            _reportService = new DapperService(educationalGroupService);
            _logService = logService;
            _educationalClassService = educationalClassService;
        }

        public ActionResult ProfessorManagement()
        {
            var professors = _professorService.GetAll().OrderBy(o => o.Id).ToList();
            return View(Mapper.Map<List<Model.Models.Professor>, List<Models.Professor>>(professors));
        }
        [Authorize]
        public ActionResult RankOfProfessorInUniversity(string term = null)
        {
            SetViewBag(title: "رتبه بندی اساتید در سطح دانشگاه", menuItem: "RankOfProfessorInUniversity");
            //// Old Methode Start
            //var counter = 0;
            //var professors = _professorService.GetAll().OrderByDescending(o => o.ProfessorScores.Sum(s => s.CurrentScore)).Select(x => new Models.Professor
            //{
            //    EducationalClasses = Mapper.Map<ICollection<Model.Models.EducationalClass>, ICollection<Models.EducationalClass>>(x.EducationalClasses),
            //    ProfessorScores = Mapper.Map<ICollection<Model.Models.ProfessorScore>, ICollection<Models.ProfessorScore>>(x.ProfessorScores),
            //    Name = x.Name,
            //    Family = x.Family,
            //    ProfessorCode = x.ProfessorCode,
            //    NationalCode = x.NationalCode,
            //    Gender = Convert.ToBoolean(x.Gender),
            //    RankInUniversity = ++counter
            //}).ToList();
            //// Old Methode End
            var termId = 0;
            ViewBag.TermList = new SelectList(_termService.GetAll().OrderByDescending(o => o.TermCode), "Id", "Name");
            if (!string.IsNullOrEmpty(term) && int.TryParse(term, out termId) && termId > 0)
            {
                var model = _reportService.GetProfessorReport(termId).General.ToList();
                foreach (var item in model)
                    item.RowNumber = model.IndexOf(item) + 1;
                return View(model);
            }
            return View();
        }
        [Authorize]
        public ActionResult ViewProfessorRankInUniversityDetails(int id = 0, int termId = 0)
        {
            //// Old Methode Start
            //var professorScores = new List<Models.ProfessorScore>();
            //if (id > 0)
            //    professorScores = Mapper.Map<List<Model.Models.ProfessorScore>, List<Models.ProfessorScore>>(_professorScoreService.GetAll().Where(w => w.Professor.ProfessorCode == id).ToList());
            //return PartialView(professorScores);
            //// Old Methode End
            if (termId == 0)
                termId = GetCurrentTerm().Id;
            ViewBag.TermId = termId;
            var model = _reportService.GetProfessorReport(termId).Detial.Where(p => p.ProfessorId == id).ToList();
            return PartialView(model);
        }
        [Authorize]
        public ActionResult RankOfProfessorInCollege(string id = null, string term = null)
        {
            SetViewBag(title: "رتبه بندی اساتید در سطح دانشکده", menuItem: "RankOfProfessorInCollege");
            var collegeId = 0;
            var termId = 0;
            ViewBag.CollegeList = new SelectList(_collegeService.GetAll(), "Id", "Name");
            ViewBag.TermList = new SelectList(_termService.GetAll().OrderByDescending(o => o.TermCode), "Id", "Name");

            if (!string.IsNullOrEmpty(id)) int.TryParse(id, out collegeId);
            var user = (Models.User)Session["UserInfo"];
            if (user != null && user.College != null)
                collegeId = user.College.Id;
            if (!string.IsNullOrEmpty(term) && int.TryParse(term, out termId) && termId > 0 && collegeId > 0)
            {
                ViewBag.CollegeName = _collegeService.Get(w => w.Id == collegeId).Name;
                //// Old Methode Start
                //    var counter = 0;
                //    var professors = _collegeService.Get(w => w.Id == collegeId).EducationalGroups.SelectMany(s => s.EducationalClasses).Where(w => w.Term.Id == termId)
                //        .Select(s => s.Professor).OrderByDescending(o => o.ProfessorScores.Where(w => w.Term != null && w.Term.Id == termId).Sum(s => s.CurrentScore)).Distinct()
                //        .Select(s => new Models.Professor
                //        {
                //            //Colleges = Mapper.Map<ICollection<Model.Models.College>, ICollection<Models.College>>(s.Colleges),
                //            //EducationalGroups = Mapper.Map<ICollection<Model.Models.EducationalGroup>, ICollection<Models.EducationalGroup>>(s.EducationalGroups),
                //            EducationalClasses = Mapper.Map<ICollection<Model.Models.EducationalClass>, ICollection<Models.EducationalClass>>(s.EducationalClasses),
                //            ProfessorScores = Mapper.Map<ICollection<Model.Models.ProfessorScore>, ICollection<Models.ProfessorScore>>(s.ProfessorScores),
                //            Name = s.Name,
                //            Family = s.Family,
                //            NationalCode = s.NationalCode,
                //            ProfessorCode = s.ProfessorCode,
                //            Gender = Convert.ToBoolean(s.Gender),
                //            RankInUniversity = ++counter
                //        }).ToList();
                //    return View(professors);
                //// Old Methode End

                var collegeList = new List<int>();
                collegeList.Add(collegeId);
                var model = _reportService.GetProfessorReport(termId, collegeList: collegeList, allColleges: false).General.ToList();
                foreach (var item in model)
                    item.RowNumber = model.IndexOf(item) + 1;
                return View(model);
            }
            //else show error
            return View();


        }

        public ActionResult RankOfProfessorInEducationalGroup(string id = null, string group = null, string term = null)
        {
            SetViewBag(title: "رتبه بندی اساتید در سطح گروه", menuItem: "RankOfProfessorInEducationalGroup");
            var collegeId = 0;
            var termId = 0;
            var groupCode = 0;

            ViewBag.CollegeList = new SelectList(_collegeService.GetAll().Where(w => 1 == 2), "Id", "Name", id);
            ViewBag.GroupList = new SelectList(_educationalGroupService.GetAll().Where(w => 1 == 2), "EducationalGroupCode", "Name", group);
            ViewBag.TermList = new SelectList(_termService.GetAll().OrderByDescending(o => o.TermCode), "Id", "Name", term);

            if (!string.IsNullOrEmpty(id)) int.TryParse(id, out collegeId);
            if (!string.IsNullOrEmpty(group)) int.TryParse(group, out groupCode);
            var user = (Models.User)Session["UserInfo"];
            if (user != null && user.College != null)
            {
                collegeId = user.College.Id;
                ViewBag.CollegeId = collegeId;
            }
            if (user != null && user.EducationalGroupCode != null)
                groupCode = (int)user.EducationalGroupCode;

            if (!string.IsNullOrEmpty(term) && int.TryParse(term, out termId) && termId > 0 && collegeId > 0 && groupCode > 0)
            {
                var educationalGroup = _educationalGroupService.Get(g => g.EducationalGroupCode == groupCode && g.Term.Id == termId);
                var college = _collegeService.Get(g => g.Id == collegeId);
                ViewBag.EducationalGroup = educationalGroup.Name;
                ViewBag.College = college.Name;
                ViewBag.CollegeId = college.Id;
                ViewBag.EducationalGroupId = educationalGroup.EducationalGroupCode;
                ViewBag.TermId = termId;

                //// Old Methode Start
                //var counter = 0;

IAUECProfessorsEvaluation.Web/Views/Professor/GroupManagerRating.cshtml
@{Layout = "~/Views/Shared/_Layout.cshtml";}
@model List<IAUECProfessorsEvaluation.Web.Models.Professor>
@using GridMvc.Html
@using IAUECProfessorsEvaluation.Core.Helper

@{
    var canChangeGroup = Session["UserInfo"] != null
        && (((IAUECProfessorsEvaluation.Web.Models.User)Session["UserInfo"]).IsAdministrator || ((IAUECProfessorsEvaluation.Web.Models.User)Session["UserInfo"]).IsPowerUser);
}

<link rel="stylesheet" href="~/Content/css/starrr.css">
<style type='text/css'>
    .tooltip {
        opacity: 0.7;
        background: #000;
    }

    .tooltip-inner {
        padding: 3px 5px;
    }

    .ui-tooltip, .arrow:after {
        background: black;
        border: 1px solid white;
    }

    .ui-tooltip {
        padding: 10px 20px;
        color: white;
        border-radius: 5px;
        box-shadow: 0 0 7px black;
    }

    .searchRow {
        border-bottom: 1px solid #ccc;
        background: #ddd;
        margin-left: -20px;
        margin-right: -20px;
        height: 70px;
    }

        .searchRow .form-group {
            margin-bottom: 0;
            margin-top: 8px;
        }

        .searchRow .control-label {
            line-height: 36px;
            font-size: 16px;
        }

    .marginTop {
        margin-top: 75px;
    }
</style>
<script src="~/Content/js/popper.min.js"></script>
<script src="~/Content/js/starrr.js"></script>


<div class="row searchRow">
    <div class="col-sm-12">
        <div class="form-group">
            <div class="row">

                <div class="col-sm-1">
                    <span class="control-label">ترم: </span>
                </div>
                <div class="col-sm-3">
                    @Html.DropDownList("TermList", (SelectList)ViewBag.TermList, "انتخاب کنید", new { @class = "form-control termList" })
                </div>
                @if (canChangeGroup)
                {
                    <div class="col-sm-1">
                        <span class="control-label">نام گروه: </span>
                    </div>
                    <div class="col-sm-3">
                        @Html.DropDownList("GroupList", (SelectList)ViewBag.GroupList, "انتخاب کنید", new { @class = "form-control groupList" })
                    </div>
                }
                <div class="col-sm-2">
                    <a href="/" id="btnSelectGroup" class="btn btn-info">انتخاب</a>
                </div>
            </div>
        </div>
    </div>
</div>

@if (Model != null)
{
    <div class="row">
        <div class="col-sm-12">
            @(Html
    .Grid(Model)
    .Columns(columns =>
    {
        columns.Add(model => model.ProfessorCode).Titled("کد استاد").SetWidth("10%").Filterable(true).Sortable(true);
        columns.Add(model => model.Family).Titled("نام استاد").RenderValueAs(o => o.Name + " " + o.Family).SetWidth("25%").Filterable(true).Sortable(true);
        columns.Add(model => model.NationalCode).Titled("کد ملی").SetWidth("15%").Filterable(true).Sortable(false);
        columns.Add(model => model.GroupMangerComments).Titled("امتیاز فعلی").SetWidth("15%").Filterable(true).Sortable(true).RenderValueAs(o=> o.GroupMangerComments != null ? o.GroupMangerComments.ToString() : "-");//.RenderValueAs(o => o.ProfessorScores.FirstOrDefault(f => f.Score.Indicator.CountOfType == "p" + (int)IndicatorProfessorName.نظر_مدیر_گروه && f.EducationalGroup.Id == ViewBag.GroupId) != null ? o.ProfessorScores.FirstOrDefault(f => f.Score.Indicator.CountOfType == "p" + (int)IndicatorProfessorName.نظر_مدیر_گروه && f.EducationalGroup.Id == ViewBag.GroupId).CurrentScore.ToString() : "-");
        columns.Add(model => model.ProfessorScores).Titled("عملیات").SetWidth("20%").Filterable(false)
            .Encoded(false).Sanitized(false)
            //.RenderValueAs(o => "<div class='starrr' id='star" + o.ProfessorCode + "'></div> <a href=\"/\" title=\"حذف امتیاز\" class=\"resetScore\" data-code=\"" + o.ProfessorCode + "\"><i class=\"fa fa-ban\"></i></a>");
            .RenderValueAs(o => "<select class=\"scoreList\"></select><input class=\"currentScore\" type=\"hidden\" value=\"" + (o.GroupMangerComments != null ? o.GroupMangerComments.ToString() : "-1") + "\" />");//o.ProfessorScores.FirstOrDefault(f => f.Score.Indicator.CountOfType == "p" + (int)IndicatorProfessorName.نظر_مدیر_گروه && f.EducationalGroup.Id == ViewBag.GroupId) != null ? o.ProfessorScores.FirstOrDefault(f => f.Score.Indicator.CountOfType == "p" + (int)IndicatorProfessorName.نظر_مدیر_گروه && f.EducationalGroup.Id == ViewBag.GroupId).CurrentScore.ToString() : "-1"
    })
    .WithMultipleFilters()
    .WithPaging(20)
    .EmptyText("موردی جهت نمایش یافت نشد.")
    .SetLanguage("fa")
    .Selectable(false)
            )
        </div>
    </div>


    <script>

        $(function () {
            var scores = [];
            var points = [];
            @foreach (var item in ViewBag.Scores) {
                <text>
            scores.push('@item.Name');
            points.push('@item.Point');
            </text>
            }

            $('.scoreList').empty().append('<option value="-1">انتخاب کنید</option>');
            $.each(scores, function(i, v){
                $('.scoreList').append('<option value="' + points[i] + '">' + v + '</option>');
            });

            var itemsCount = 0;
            var modelCount = $('.scoreList').length;
            $('.scoreList').each(function(){
                var item = $(this);
                if(item.parent().find('.currentScore').val() == "-1"){
                    item.val("-1");
                    itemsCount++;
                }
                else{
                    var id = $(this).parent().parent().find('td:nth-child(1)').html();
                    $.ajax({
                        url: '/Professor/GetCurrentStar',
                        type: 'POST',
                        data: { currentRateData: item.parent().find('.currentScore').val(), countOfType: 'p' + @((int)IndicatorProfessorName.نظر_مدیر_گروه)},
                        success : function(val){
                            item.val(val);
                            itemsCount++;
                            if(itemsCount === modelCount)
                                $('.loadingWrapper').hide();
                            else
                                $('.loadingWrapper').show();
                        }
                    });
                }
            });

            $('.scoreList').change(function () {
                $('.loadingWrapper').show();
                var selectedValue = $(this).val();
                var el = $(this);
                if(selectedValue == "-1"){
                    $.ajax({
                        url: '/Professor/DeleteGroupManagerRate',
                        type: 'POST',
                        data: {code: el.parent().parent().find('td:nth-child(1)').html(), groupId: @(ViewBag.GroupId), termId: @(ViewBag.TermId)},
                        success: function(result){
                            el.parent().parent().find('td:nth-child(4)').html("-");
                            el.parent().find('.currentScore').val("-1");
                            $('.loadingWrapper').hide();
                        }
                    });
                }
                else{
                    var pc = el.parent().parent().find('td:nth-child(1)').html();
                    $.ajax({
                        url: '/Professor/AddOrUpdateRate',
                        type: 'POST',
                        data: { professorCode: pc, rateIndex: selectedValue, countOfType: 'p' + @((int)IndicatorProfessorName.نظر_مدیر_گروه), groupId: @(ViewBag.GroupId), termId: @(ViewBag.TermId)},
                        success: function (result) {
                            el.parent().parent().find('td:nth-child(4)').html(result);
                            el.parent().find('.currentScore').val(result);
                            $('.loadingWrapper').hide();
                        }
                    });
                }
            });




            @*@foreach (var item in Model) {
        var id = "#star" + item.ProfessorCode;
        <text>
            var itemsCount = 0;
            var modelCount = @Model.Count();
            $.ajax({
                url: '/Professor/GetCurrentStar',
                type: 'POST',
                data: { currentRateData: @item.GroupMangerComments, countOfType: 'p' + @((int)IndicatorProfessorName.نظر_مدیر_گروه)},
                success : function(val){
                    if(itemsCount == 0)
                        setTimeout(function(){$('.loadingWrapper').show();}, 50);
                    $('@id').starrr({
                        max: @ViewBag.Scores.Count,
                        rating: val,
                        change: function(e, value){
                            e.preventDefault();
                            var pc = $(e.target).parent().parent().find('td:nth-child(1)').html();
                            $.ajax({
                                url: '/Professor/AddOrUpdateRate',
                                type: 'POST',
                                data: { professorCode: pc, rateIndex: value, countOfType: 'p' + @((int)IndicatorProfessorName.نظر_مدیر_گروه)},
                                success: function (result) {
                                    $(e.target).parent().parent().find('td:nth-child(4)').html(result);
                                }
                            });
                        }
                    });
                    itemsCount++;
                    if(itemsCount === modelCount)
                    {
                        $('.starrr').each(function(i){
                            $(this).find('a').each(function(ii, el){
                                $(this).attr('title',scores[scores.length - ii - 1])
                            });
                        });
                        $('.loadingWrapper').hide();
                    }
                }
            });
            </text>
    }*@

            //$('body').tooltip({
            //    selector: '.starrr',
            //    track: true,
            //    position: {
            //        my: "center bottom-20",
            //        at: "center bottom"
            //    }
            //});



            //$('.resetScore').click(function(e){
            //    e.preventDefault();
            //    $.ajax({
            //        url: '/Professor/DeleteGroupManagerRate',
            //        type: 'POST',
            //        data: {code: $(this).data("code")},
            //        success: function(result){
            //            //window.location.href = '/Professor/GroupManagerRating'
            //            location.reload();
            //        }
            //    });
            //});




        });
    </script>

}
else if (((IAUECProfessorsEvaluation.Web.Models.User)Session["UserInfo"]) != null && !(((IAUECProfessorsEvaluation.Web.Models.User)Session["UserInfo"]).IsAdministrator || ((IAUECProfessorsEvaluation.Web.Models.User)Session["UserInfo"]).IsPowerUser))
{
    <div class="alert alert-danger marginTop">
        <span>دانشکده ای برای شما تعیین نشده است.</span>
    </div>
}
<script>
    $(function () {
        @if(Model != null)
        {
            <text>
        $('#GroupList').val(@ViewBag.GroupId);
        $('#TermList').val(@ViewBag.TermId);
        </text>
        }
        $(document).on('click', '#btnSelectGroup', function (e) {
            e.preventDefault();


            @if (canChangeGroup)
            {
                <text>
            if($('#GroupList').val() !== '' && $('#TermList').val() !== ''){
                $('.loadingWrapper').show();
                window.location.href = "/Professor/GroupManagerRating/?group=" + $('#GroupList').val() + "&termId=" + $('#TermList').val();
            }
            </text>
            }
            else
            {
                <text>
            if($('#TermList').val() !== ''){
                $('.loadingWrapper').show();
                window.location.href = "/Professor/GroupManagerRating/?termId=" + $('#TermList').val();
            }
                </text>
            }


            @*$.ajax({
                url: '@Url.Action("GroupManagerRatingForAdmin", "Professor")',
                type: 'POST',
                data: { 'group': $('#GroupList').val() },
                success: function (data) {
                    window.location.href = "/Professor/GroupManagerRating"
                }
            });*@
        });

        $('.termList').on('change', function () {
            $('.groupList').html('<option>انتخاب کنید</option>');
            if ($('.termList').val() != '') {
                $('.loadingWrapper').show();
                $.ajax({
                    url: '@Url.Action("GetGroupsByTermId", "Professor")',
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    method: 'GET',
                    data: { termId: $('.termList').val() },
                    success: function (e) {
                        if (e != null) {
                            $.each(e, function (i, v) {
                                $('.groupList').append('<option value="' + v.EducationalGroupCode + '">' + v.Name +'</option>')
                            });
                        }
                        $('.loadingWrapper').hide();
                    }
                });
            }
        });
    });
</script>

IAUECProfessorsEvaluation.Web/Views/Professor/ViewProfessorRankInUniversityDetails.cshtml
@using IAUECProfessorsEvaluation.Web.Models.Utility
@model List<IAUECProfessorsEvaluation.Data.ReportModel.ProfessorDetialReportModel>

<style>
    .title {
        padding: 0px 10px;
        margin-bottom:10px;
    }

        .title > div {
            border-bottom: 2px solid #ccc;
            font-size: 1em;
            font-weight: bold;
            line-height: 2em;
            padding-right: 10px;
        }

    .professorInfo {
        margin-bottom: 15px;
        border-bottom: 1px solid #ccc;
        line-height: 30px;
    }

    .professorImage {
        position: absolute;
        left: 10px;
        top: -10px;
        bottom: 0;
        margin: auto;/**/
        height: 70px;
        overflow: hidden;
        width: 70px;
        max-width: 70px;
        border: 2px solid #ccc;
        border-radius: 50%;
        text-align: center;
        white-space: nowrap;
        display: inline-block;
        margin-top: 10px;
        float: left;
    }

        .professorImage img {
            width: 100%;
            position: absolute;
            top: 10px;
            left: 0;
            right: 0;
            /*bottom: 0;*/
            margin: auto;
        }
            .avgScore {
        font-size: 14px;
        font-weight: bold;
        text-align: center;
        border-top: 1px solid #ddd;
    }
            .progress{
        margin-bottom: 10px;
    }
            hr{padding:0 !important;}
</style>

<div class="container" style="width: 98%">
    <div class="row">
        <div class="title col-xs-12">
            <div>مشخصات استاد</div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-8">
            <div class="row">
                <div class="col-xs-4">نام و نام خانوادگی:</div>
                <div class="col-xs-5"> @Model.FirstOrDefault().FullName</div>
            </div>
            <div class="row">
                <div class="col-xs-4">کد استاد:</div>
                <div class="col-xs-5"> @Model.FirstOrDefault().ProfessorCode</div>
            </div>
            <div class="row">
                <div class="col-xs-4">کد ملی:</div>
                <div class="col-xs-5"> @Model.FirstOrDefault().NationalCode</div>
            </div>

        </div>
        <div class="col-xs-4">
            <div class="professorImage">
                <img src="~/Content/images/person.png" />
            </div>

        </div>

    </div>
    <hr />
    <div class="row">
        <div class="title col-xs-4">
            <div>عنوان شاخص</div>
        </div>
        <div class="title col-xs-8">
            <div>میانگین امتیاز</div>
        </div>
    </div>
    @foreach (var item in Model.OrderBy(x => x.IndicatorName))
    {
        if (!string.IsNullOrEmpty(item.AvgScore.ToString()))
        {
            <div class="row">
                <div class="col-xs-4">
                    <div>@item.IndicatorName</div>
                    <div><span>میزان اهمیت: </span><span>@item.RationName (x @item.RationValue)</span></div>
                </div>
                <div class="col-xs-8">

                    <div>@((item.AvgScore / item.RationValue)?.GetScoreName(item.IndicatorId, item.ProfessorCode, ((int)ViewBag.TermId)))</div>
                    <div class="progress" style="border-radius: 5px;">
                        <div class="progress-bar @((item.AvgScore / item.RationValue)?.GetCssClassForProgressBar())" role="progressbar" aria-valuenow="@(item.AvgScore / item.RationValue)" aria-valuemin="0" aria-valuemax="100" style="width: @(item.AvgScore / item.RationValue)%;">
                            <span style="line-height: 20px;">@(item.AvgScore / item.RationValue)</span>
                        </div>
                    </div>
                    <div class="avgScore">@item.AvgScore</div>



                </div>

            </div>
        }
        else
        {
            <div class="row" style="display: block;background-color: antiquewhite">
                <div class="col-xs-4">
                    <div>@item.IndicatorName</div>
                    <div><span>میزان اهمیت: </span><span>@item.RationName (x @item.RationValue)</span></div>
                </div>
                <div class="col-xs-8">

                    <div class="alert alert-warning" style="display: block; padding: initial; margin: initial; border-color: #2a3f54; background-color: #2a3f54;text-align: center">
                        <h5>موجود نمی باشد</h5>
                    </div>

                </div>

            </div>
        }
        <hr class="col-xs-12" />
    }


</div>