IAUECProfessorsEvaluation.Web/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web.Mvc;
using IAUECProfessorsEvaluation.Service.IService;
using IAUECProfessorsEvaluation.Web.Models.ViewModel;
using System.IO;
using IAUECProfessorsEvaluation.Data.ReportModel;
using IAUECProfessorsEvaluation.Service.Service;
using Microsoft.Ajax.Utilities;
using WebGrease.Css.Extensions;
using System.Web.Script.Serialization;
using IAUECProfessorsEvaluation.Web.Models.ReportModel;
using IAUECProfessorsEvaluation.Web.Models.Utility;
using NPOI.HSSF.UserModel;
using CollegeReportModel = IAUECProfessorsEvaluation.Data.ReportModel.CollegeReportModel;
using AutoMapper;
using IAUECProfessorsEvaluation.Data.Infrastructure;
using IAUECProfessorsEvaluation.Data.Repository;
using IAUECProfessorsEvaluation.Model.Models;
using IAUECProfessorsEvaluation.Service.Service.Sync;
using IAUECProfessorsEvaluation.Core.Helper;
using NPOI.HSSF.Util;
using NPOI.SS.UserModel;
using NPOI.SS.Util;

namespace IAUECProfessorsEvaluation.Web.Controllers
{
    [Authorize]
    public class ReportsController : Controller
    {
        #region Fields
        private ICollegeService _collegeService;
        private IEducationalGroupService _educationalGroupService;
        private IEducationalClassService _educationalClassService;
        private IIndicatorService _indicatorService;
        private ITermService _termService;
        private IProfessorService _professorService;
        private IProfessorScoreService _professorScoreService;
        private DapperService _reportService;
        private IRoleAccessService _roleAccessService;
        private IUserRoleService _userRoleService;
        private ILogService _logService;
        private int? _userCollegeId;
        private int? _userGroupCode;
        #endregion

        #region Ctor
        public ReportsController(
            ICollegeService collegeService,
            IEducationalGroupService educationalGroupService,
            IEducationalClassService educationalClassService,
            IIndicatorService indicatorService,
            ITermService termService,
            IEducationalGroupScoreService educationalGroupScoreService,
            IProfessorScoreService professorScoreService,
            IProfessorService professorService,
            IRoleAccessService roleAccessService,
            IUserRoleService userRoleService,
            ILogService logService
            )
        {

            _collegeService = collegeService;
            _educationalGroupService = educationalGroupService;
            _educationalClassService = educationalClassService;
            _indicatorService = indicatorService;
            _termService = termService;
            _professorService = professorService;
            _professorScoreService = professorScoreService;
            _reportService = new DapperService(educationalGroupService);
            _roleAccessService = roleAccessService;
            _userRoleService = userRoleService;


            _logService = logService;
        }
        #endregion


        public ActionResult GetColleges()
        {
            SetUser();

            if (_userCollegeId != null && _userCollegeId != 0)
            {
                var colleges = _collegeService.GetMany(x => x.IsActive == true && x.Id == _userCollegeId)
                    .Select(x => new SelectCustomeList { Id = x.Id, Name = x.Name }).ToList();
                return Json(colleges.OrderByDescending(x => x.Id), JsonRequestBehavior.AllowGet);
            }
            else
            {
                var colleges = _collegeService.GetMany(x => x.IsActive == true)
                    .Select(x => new SelectCustomeList { Id = x.Id, Name = x.Name }).ToList();
                return Json(colleges.OrderByDescending(x => x.Id), JsonRequestBehavior.AllowGet);
            }
        }

        private void SetUser()
        {
            var user = (Models.User)Session["UserInfo"];
            if (user != null && user.College != null)
                _userCollegeId = user.College.Id;
            if (user != null && user.EducationalGroupCode != null)
                _userGroupCode = user.EducationalGroupCode;
        }

        public ActionResult GetGroups(string collegesList, string term, bool all)
        {
            SetUser();

            if (_userGroupCode != null && _userGroupCode != 0)
            {

                var termId = Convert.ToUInt32(term);
                List<SelectCustomeList> model;
                if (string.IsNullOrEmpty(collegesList) || all)
                {
                    model = _educationalGroupService.GetMany(x => x.IsActive == true && x.Term.Id == termId
                    && x.EducationalGroupCode == _userGroupCode)
                        .Select(x => new SelectCustomeList { Id = x.Id, Name = x.Name }).OrderBy(x => x.Name).ToList();
                }
                else
                {
                    var colleges = new JavaScriptSerializer().Deserialize<List<int>>(collegesList);
                    model = _educationalGroupService.GetMany(x =>
                        x.IsActive == true
                        && x.Term.Id == termId
                        && colleges.Contains(x.College.Id)
                        && x.EducationalGroupCode == _userGroupCode
                        )
                        .Select(x => new SelectCustomeList { Id = x.Id, Name = x.Name }).OrderBy(x => x.Name).ToList();
                }


                return Json(model, JsonRequestBehavior.AllowGet);

            }
            else
            {
                var termId = Convert.ToUInt32(term);
                List<SelectCustomeList> model;
                if (string.IsNullOrEmpty(collegesList) || all)
                {
                    model = _educationalGroupService.GetMany(x => x.IsActive == true && x.Term.Id == termId)
                        .Select(x => new SelectCustomeList { Id = x.Id, Name = x.Name }).OrderBy(x => x.Name).ToList();
                }
                else
                {
                    var colleges = new JavaScriptSerializer().Deserialize<List<int>>(collegesList);
                    model = _educationalGroupService.GetMany(x => x.IsActive == true && x.Term.Id == termId && colleges.Contains(x.College.Id))
                        .Select(x => new SelectCustomeList { Id = x.Id, Name = x.Name }).OrderBy(x => x.Name).ToList();
                }


                return Json(model, JsonRequestBehavior.AllowGet);

            }
        }

        public ActionResult GetProfessores(string groupList, string term, bool all)
        {


            var termId = Convert.ToUInt32(term);

            List<SelectCustomeList> model;
            if (string.IsNullOrEmpty(groupList) || all)
            {
                model = _professorService.GetMany(x => x.IsActive == true && x.Term.Id == termId)
                    .Select(x => new SelectCustomeList { Id = x.Id, Name = (x.Name + ' ' + x.Family) }).OrderBy(x => x.Name).ToList();
            }
            else
            {
                var groups = new JavaScriptSerializer().Deserialize<List<int>>(groupList);
                var professors = _educationalClassService
                    .GetMany(x => x.IsActive == true && groups.Contains(x.EducationalGroup.Id)).Select(x => x.Professor.Id).Distinct().ToList();

                model = _professorService.GetMany(x =>
                x.IsActive == true
                && x.Term.Id == termId
                && professors.Contains(x.Id)
                )
                   .Select(x => new SelectCustomeList { Id = x.Id, Name = (x.Name + ' ' + x.Family) }).OrderBy(x=>x.Name).ToList();
            }

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        //[OutputCache(Duration = 600000)]
        public ActionResult Index()
        {
            SetUser();
            SetViewBag(title: "گزارش ساز", menuItem: "ReportsIndex");
            ViewBag.lastUpdate = _logService.LastUpdate();

            var model = new ReportingViewMoel();
            var indicators = _indicatorService.GetAllWithObjectTypeAndScore().Where(x => x.IsActive == true)
                .Select(
                    m => new IndicatorViewModel
                    {
                        Id = m.Id,
                        Name = m.Name,
                        ObjectTypeId = m.ObjectType.Id,
                        Scores = m.Scores.Where(x => x.IsActive == true).Select(
                            n => new ScoreViewModel { Id = n.Id, Name = n.Name }).ToList(),
                        CountOfType = string.IsNullOrEmpty(m.CountOfType) ? "" : m.CountOfType
                    }).ToList();



            model.IndicatorsForGroup = indicators.Where(x => x.ObjectTypeId == 2 && x.CountOfType.Contains('g')).ToList();
            model.IndicatorsForProfessor = indicators.Where(x => x.ObjectTypeId == 1 && x.CountOfType.Contains('p')).ToList();
            model.Terms = _termService.GetAll().Where(t => string.CompareOrdinal(t.TermCode, "96-97-2") >= 0).OrderByDescending(o => o.TermCode).Select(m => new TermViewModel { Id = m.Id, Name = m.Name, TermCode = m.TermCode }).ToList();
            model.ReportLevleType = ReportLevle.GetReportLeveles(_userCollegeId, _userGroupCode);
            model.SortingList = SortingViewModel.GetSortingList();
            return View(model);
        }

        public JsonResult ServerFiltering_GetColleges(string text)
        {

            List<CollegeViewModel> colleges = null;
            if (!string.IsNullOrEmpty(text))
            {
                if (text.Contains(","))
                {
                    var textSplited = text.Split(',');
                    text = textSplited[(textSplited.Length - 1)];
                }

                colleges = _collegeService.GetAll()
                    .Where(x => x.IsActive == true)
                    .Select(x => new CollegeViewModel { Id = x.Id, Name = x.Name })

IAUECProfessorsEvaluation.Web/Views/Reports/CollegeDetails.cshtml
@model System.Collections.Generic.List<IAUECProfessorsEvaluation.Data.ReportModel.GroupReportModel>


@using IAUECProfessorsEvaluation.Web.Models.Utility

<style>
    .title {
        padding: 0px 10px;
        margin-bottom:15px;
    }

        .title > div {
            border-bottom: 2px solid #ccc;
            font-size: 1em;
            font-weight: bold;
            line-height: 2em;
            padding-right: 10px;
        }

    .professorInfo {
        margin-bottom: 15px;
        border-bottom: 1px solid #ccc;
        line-height: 30px;
    } 

    .topProfessorImage {
        /*position: absolute;
        left: 10px;
        top: 0;
        bottom: 0;
        margin: auto;*/
        height: 70px;
        overflow: hidden;
        width: 70px;
        max-width: 70px;
        border: 2px solid #ccc;
        border-radius: 50%;
        text-align: center;
        white-space: nowrap;
        display: inline-block;
        margin-top: 10px;
        float: left;
    }

        .topProfessorImage img {
            width: 100%;
            /*position: absolute;
            left: 0;
            right: 0;
            top: 0;
            bottom: 0;*/
            margin: auto;
        }
            .k-widget .container * {
        box-sizing: border-box;
        -webkit-box-sizing: border-box;
    }
</style>

<div class="container" style="width: 98%">
    <div class="row">
        <div class="title col-xs-12">
            <div>مشخصات دانشکده</div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-6">
            <div class="row">
                <div class="col-xs-4">نام دانشکده:</div>
                <div class="col-xs-5"> @Model.FirstOrDefault().CollegeName</div>
            </div>
            <div class="row">
                <div class="col-xs-4">کد دانشکده:</div>
                <div class="col-xs-5"> @Model.FirstOrDefault().CollegeCode</div>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="row">
                <div class="col-xs-5">امتیاز نهایی دانشکده:</div>
                <div class="col-xs-5"> @Model.FirstOrDefault().CollegeScore</div>
            </div>
        </div>

    </div>
    <hr />
    <div class="row">
        <div class="title col-xs-4">
            <div>گروه ها</div>
        </div>
        <div class="title col-xs-8">
            <div>امتیاز کسب گردید شده</div>
        </div>
    </div>
    @foreach (var item in Model.OrderByDescending(x=>x.GroupScore))
    {

        <div class="row">
                <div class="col-xs-4">
                    <div>@item.IndicatorName</div>
                    <div><span>نام گروه: </span><span>@item.GroupName</span></div>
                </div>
                <div class="col-xs-8">
                    <div>@item.GroupScore</div>



                </div>

            </div>
                <hr class="col-xs-12" />
    }


            </div>

IAUECProfessorsEvaluation.Web/Views/Reports/CollegeReport.cshtml
@using IAUECProfessorsEvaluation.Data.ReportModel
@model List<GroupReportModel>
    @using Kendo.Mvc.UI;
@using NPOI.SS.Formula.Functions
    @{
        ViewBag.Title = "گزارش دانشکده ها";
        Layout = "~/Views/Shared/_Layout2.cshtml";
        var pageSize = 20;

    }


    <br />
    <br />
    <br />
    <br />

 

<div class="row">
    <div class="col-xs-12">
        <div class="row alert alert-info" style="background-color: rgb(42, 63, 84);border-color: rgba(42, 63, 84,.88);">
            <h4 style="text-align: center">رتبه بندی دانشکده ها</h4>

        </div>

        <div class="row">
            @(Html.Kendo().Grid<GroupReportModel>(Model)
                  .Name("Generalresualt")
                  .Columns(columns =>
                  {
                      columns.Bound(x => x.RowNumber).ClientTemplate("#= renderNumber1() #").Filterable(false).Sortable(false).Title("ردیف").HeaderHtmlAttributes(new { style = "text-align: center;" }).HtmlAttributes(new { style = "text-align: center;" });
                      columns.Bound(p => p.CollegeCode).Title("کد دانشکده").HeaderHtmlAttributes(new { style = "text-align: center;" }).HtmlAttributes(new { style = "text-align: center;" });
                      columns.Bound(p => p.CollegeName).Title("نام دانشکده").HeaderHtmlAttributes(new { style = "text-align: center;" }).HtmlAttributes(new { style = "text-align: center;" });
                      columns.Bound(p => p.CollegeScore).Title("امتیاز دانشکده").HeaderHtmlAttributes(new { style = "text-align: center;" }).HtmlAttributes(new { style = "text-align: center;" });
                      columns.Bound(p => p.CollegeId).Hidden();
                      columns.Command(p => p.Custom("مشاهده").Click("showDetails").DataRouteValues(x =>
                      {
                          x.Add(o => o.CollegeId);
                      }).HtmlAttributes(new { style = "text-align: center;" })).Title("جزئیات").HeaderHtmlAttributes(new { style = "text-align: center;" }).HtmlAttributes(new { style = "text-align: center;" });
                  })
                  .HtmlAttributes(new { style = "height: 550px;" })
                  .Pageable(pageable => pageable
                      .Input(true)
                      .Numeric(false)
                  .Messages(m=>m.AllPages("تمام صفحات").Page("صفحه").Of(" ").Display("").Empty("هیچ مقدار").ItemsPerPage("تعداد نسبت به صفحه")))
                  .ToolBar(tools => tools.Custom().Text("گزارش با جزئیات").Url(Url.Action("CollegeDetailsPrint","Reports")))
                  .ToolBar(tools => tools.Custom().Text("گزارش به صورت کلی").Url(Url.Action("CollegeGeneralPrint", "Reports")))
                  .ToolBar(tools => tools.Custom().Text("بازگشت به گزارش ساز").Url(Url.Action("Index", "Reports")))
                  //.ToolBar(tools => tools.Excel().Text("  خروجی اکسل  ").IconClass("fff k-icon k-i-excel").HtmlAttributes(new { style = "padding-right: 5px;" }))
                  //.ToolBar(tools => tools.Custom().Text("خروجی قابل چاپ").IconClass("fff k-icon k-i-pdf").Action("CollegeGeneralPrint", "Reports"))
                  .Excel(excel => excel
                      .FileName("GroupGeneralExcelExport.xlsx")
                      .Filterable(true)
                      .AllPages(true))
                  .Sortable()
                  .Scrollable(scr => scr.Height(430))
                  .Filterable(filterable => filterable.Operators(
                      operators => operators.ForString(
                          str => str.Clear()
                              .Contains("شامل")
                              .DoesNotContain("شامل نیست")
                              .IsEqualTo("برابر")
                              .IsNotEqualTo("برابر نیست")
                          )
                          .ForNumber(num => num.Clear()
                              .IsEqualTo("برابر")
                              .IsNotEqualTo("برابر نیست")
                              .IsGreaterThan("بزرگتر")
                              .IsGreaterThanOrEqualTo("بزرگتر مساوی")
                              .IsLessThan("کوچکتر")
                              .IsLessThanOrEqualTo("کوچکتر مساوی")
                          )

                      ).Messages(msg => msg.And("و").Clear("پاک").Filter("فیلتر").Or("یا").Info("جستجو:")))
                  .DataSource(dataSource => dataSource
                      .Ajax()
                      .PageSize(pageSize)
                      .ServerOperation(false)
                  )
                  )
        </div>
    </div>
</div>



@(Html.Kendo().Window().Name("Details")
    .Title("جزئیات")
    .Visible(false)
    .Modal(true)
    .Draggable(true)
      .Scrollable(true)
      .Height(600)
      
    .Width(800)

)

<script type="text/x-kendo-template" id="template">
    <div id="details-container">
    </div>
</script>

<script type="text/javascript">
    var detailsTemplate = kendo.template($("#template").html());

    function showDetails(e) {
        e.preventDefault();

        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));

                    $.ajax({
                    url: '@Url.Action("CollegeDetails", "Reports")',
                    type: 'Get',
                    data: { 'collegeId': dataItem["CollegeId"] }
                })
                .done(function (resualt) {
                var wnd = $("#Details").data("kendoWindow");
                wnd.content(resualt);
                wnd.center().open();

                });


    }
</script>

<style type="text/css">
    #details-container {
        padding: 10px;
    }

    .k-window-actions {
        left: .3em;
        right: initial !important;
    }

    #details-container h2 {
        margin: 0;
    }

    #details-container em {
        color: #8c8c8c;
    }

    #details-container dt {
        margin: 0;
        display: inline;
    }
</style>


<script type="text/javascript">
    function error_handler(e) {
        alert("Server error");
    }
    var rowNumber = 0;
    var rowNumber1 = 0;

    function resetRowNumber() {
        rowNumber = 0;
    }
    function resetRowNumber1() {
        rowNumber1 = 0;
    }
    function renderNumber() {
        return ++rowNumber;
    }
    function renderNumber1() {
        return ++rowNumber1;
    }
    function onSorting(arg) {
        resetRowNumber();
    }
    function onSorting1(arg) {
        resetRowNumber1();
    }
    function onFiltering(arg) {
        resetRowNumber();
    }
    function onFiltering1(arg) {
        resetRowNumber1();
    }
    function onPaging(arg) {
        rowNumber = (arg.page - 1) * @pageSize;
    }
    function onPaging1(arg) {
        rowNumber1 = (arg.page - 1) * @pageSize;
    }
    </script>

IAUECProfessorsEvaluation.Web/Views/Reports/GroupReport.cshtml
@using IAUECProfessorsEvaluation.Data.ReportModel
@model List<GroupReportModel>
@using Kendo.Mvc.UI;
@{
    ViewBag.Title = "گزارش گروه های آموزشی";
    Layout = "~/Views/Shared/_Layout2.cshtml";
    var pageSize = 20;
    var modelcount = Model.FirstOrDefault()?.FlawIndicatiors != null ? Model.FirstOrDefault()?.FlawIndicatiors.Count : 0;

    var modelWar = Model.FirstOrDefault()?.FlawIndicatiors;


}


<br />
@if (modelcount > 0)
{
    <div class="row" style="margin: 0 auto">
        <div class="row alert alert-warning">
            <h4>اطلاعات وارده گروه ها برای شاخص های ذیل دارای نقص می باشد</h4>
            <div class="col-xs-6">
                <ul>
                    @for (var i = 0; i < (modelcount - modelcount / 2); i++)
                    {
                        <li>
                            @if (modelWar != null)
                            {
                                @modelWar[i]
                            }
                        </li>
                    }
                </ul>
            </div>
            <div class="col-xs-6">
                <ul>
                    @for (var j = (modelcount - 1); j > (modelcount / 2); j--)
                    {
                        if (!((modelcount / 2) == 0 && (modelcount - 1) == 0) && modelWar != null)
                        {
                            <li>

                                @modelWar[j.Value]
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
}



<div class="row">
    <div class="col-xs-12">
        <div class="row alert alert-info" style="background-color: rgb(42, 63, 84);border-color: rgba(42, 63, 84,.88);">
            <h4 style="text-align: center">رتبه بندی گروه های آموزشی</h4>

        </div>

        <div class="row">
            @(Html.Kendo().Grid<GroupReportModel>(Model)
                                          .Name("Generalresualt")
                                          .Columns(columns =>
                                          {
                                              columns.Bound(x => x.RowNumber).ClientTemplate("#= renderNumber1() #").Filterable(false).Sortable(false).Title("ردیف").HeaderHtmlAttributes(new { style = "text-align: center;" }).HtmlAttributes(new { style = "text-align: center;" });
                                              columns.Bound(p => p.GroupCode).Title("کد گروه").HeaderHtmlAttributes(new { style = "text-align: center;" }).HtmlAttributes(new { style = "text-align: center;" });
                                              columns.Bound(p => p.GroupName).Title("نام گروه").HeaderHtmlAttributes(new { style = "text-align: center;" }).HtmlAttributes(new { style = "text-align: center;" });
                                              columns.Bound(p => p.GroupManagerFirstName).Title("نام مدیر گروه").HeaderHtmlAttributes(new { style = "text-align: center;" }).HtmlAttributes(new { style = "text-align: center;" }).ClientTemplate("<span># if(GroupManagerFirstName != null){# #=GroupManagerFirstName# #=GroupManagerLastName# #} else {# نامشخص #}#</span>");
                                              columns.Bound(p => p.CollegeName).Title("نام دانشکده").HeaderHtmlAttributes(new { style = "text-align: center;" }).HtmlAttributes(new { style = "text-align: center;" });
                                              columns.Bound(p => p.AvgProfessorScoreGroup).Title("میانگین نمرات اساتید").HeaderHtmlAttributes(new { style = "text-align: center;" }).HtmlAttributes(new { style = "text-align: center;" });
                                              columns.Bound(p => p.GroupScore).Title("امتیاز گروه").HeaderHtmlAttributes(new { style = "text-align: center;" }).HtmlAttributes(new { style = "text-align: center;" });
                                              columns.Bound(p => p.GroupId).Hidden();
                                              columns.Command(p => p.Custom("مشاهده").Click("showDetails").DataRouteValues(x =>
                                              {
                                                  x.Add(o => o.GroupId);
                                              }).HtmlAttributes(new { style = "text-align: center;" })).Title("جزئیات").HeaderHtmlAttributes(new { style = "text-align: center;" }).HtmlAttributes(new { style = "text-align: center;" });
                                          })
                                          .HtmlAttributes(new { style = "height: 550px;" })
                                          .Pageable(pageable => pageable
                                              .Input(true)
                                              .Numeric(false)
                                          .Messages(m => m.AllPages("تمام صفحات").Page("صفحه").Of(" ").Display("").Empty("هیچ مقدار").ItemsPerPage("تعداد نسبت به صفحه")))
                                          .ToolBar(tools => tools.Custom().Text("گزارش با جزئیات").Url(Url.Action("GroupDetailsPrint", "Reports")))
                                          .ToolBar(tools => tools.Custom().Text("گزارش به صورت کلی").Url(Url.Action("GroupGeneralPrint", "Reports")))
                                          .ToolBar(tools => tools.Custom().Text("بازگشت به گزارش ساز").Url(Url.Action("Index", "Reports")))
                                          //.ToolBar(tools => tools.Excel().Text("  خروجی اکسل  ").IconClass("fff k-icon k-i-excel").HtmlAttributes(new { style = "padding-right: 5px;" }))
                                          //.ToolBar(tools => tools.Custom().Text("خروجی قابل چاپ").IconClass("fff k-icon k-i-pdf").Action("CollegeGeneralPrint", "Reports"))
                                          .Excel(excel => excel
                                              .FileName("GroupGeneralExcelExport.xlsx")
                                              .Filterable(true)
                                              .AllPages(true))
                                          .Sortable()
                                          .Events(events =>
                                          {
                                              events.Change("resetRowNumber1")
                                                  .Sort("onSorting1")
                                                  .Filter("onFiltering1")
                                                  .Page("onPaging1");
                                          })
                                          .Scrollable(scr => scr.Height(430))
                                          .Filterable(filterable => filterable.Operators(
                                              operators => operators.ForString(
                                                  str => str.Clear()
                                                      .Contains("شامل")
                                                      .DoesNotContain("شامل نیست")
                                                      .IsEqualTo("برابر")
                                                      .IsNotEqualTo("برابر نیست")
                                                  )
                                                  .ForNumber(num => num.Clear()
                                                      .IsEqualTo("برابر")
                                                      .IsNotEqualTo("برابر نیست")
                                                      .IsGreaterThan("بزرگتر")
                                                      .IsGreaterThanOrEqualTo("بزرگتر مساوی")
                                                      .IsLessThan("کوچکتر")
                                                      .IsLessThanOrEqualTo("کوچکتر مساوی")
                                                  )

                                              ).Messages(msg => msg.And("و").Clear("پاک").Filter("فیلتر").Or("یا").Info("جستجو:")))
                                          .DataSource(dataSource => dataSource
                                              .Ajax()
                                              .PageSize(pageSize)
                                              .ServerOperation(false)
                                          )
            )
        </div>
    </div>
</div>



@(Html.Kendo().Window().Name("Details")
                .Title("جزئیات")
                .Visible(false)
                .Modal(true)
                .Draggable(true)
                  .Scrollable(true)
                  .Height(600)

                .Width(800)

)

<script type="text/x-kendo-template" id="template">
    <div id="details-container">
    </div>
</script>

<script type="text/javascript">
    var detailsTemplate = kendo.template($("#template").html());

    function showDetails(e) {
        e.preventDefault();

        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));

                    $.ajax({
                    url: '@Url.Action("GroupDetails", "Reports")',
                    type: 'Get',
                    data: { 'groupId': dataItem["GroupId"] }
                })
                .done(function (resualt) {
                var wnd = $("#Details").data("kendoWindow");
                wnd.content(resualt);
                wnd.center().open();

                });


    }
</script>

<style type="text/css">
    #details-container {
        padding: 10px;
    }

    .k-window-actions {
        left: .3em;
        right: initial !important;
    }

    #details-container h2 {
        margin: 0;
    }

    #details-container em {
        color: #8c8c8c;
    }

    #details-container dt {
        margin: 0;
        display: inline;
    }
</style>


<script type="text/javascript">
    function error_handler(e) {
        alert("Server error");
    }
    var rowNumber = 0;
    var rowNumber1 = 0;

    function resetRowNumber() {
        rowNumber = 0;
    }
    function resetRowNumber1() {
        rowNumber1 = 0;
    }
    function renderNumber() {
        return ++rowNumber;
    }
    function renderNumber1() {
        return ++rowNumber1;
    }
    function onSorting(arg) {
        resetRowNumber();
    }
    function onSorting1(arg) {
        resetRowNumber1();
    }
    function onFiltering(arg) {
        resetRowNumber();
    }
    function onFiltering1(arg) {
        resetRowNumber1();
    }
    function onPaging(arg) {
        rowNumber = (arg.page - 1) * @pageSize;
    }
    function onPaging1(arg) {
        rowNumber1 = (arg.page - 1) * @pageSize;
    }
</script>