IAUECProfessorsEvaluation.Web/Controllers/EducationalClassesController.cs
using AutoMapper;
using IAUECProfessorsEvaluation.Core.Helper;
using IAUECProfessorsEvaluation.Model.Models;
using IAUECProfessorsEvaluation.Service.IService;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.OleDb;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;

namespace IAUECProfessorsEvaluation.Web.Controllers
{
    public class EducationalClassesController : Controller
    {
        private IEducationalClassService _educationalClassService;
        private IEducationalGroupService _educationalGroupService;
        private IProfessorScoreService _professorScoreService;
        private ITermService _termService;
        private IScoreService _scoreService;
        private IRoleAccessService _roleAccessService;
        private IUserRoleService _userRoleService;
        private IProfessorService _professorService;
        private IIndicatorService _indicatorService;

        public EducationalClassesController(
            IEducationalClassService educationalClassService
            , IEducationalGroupService educationalGroupService
            , ITermService termService
            , IProfessorScoreService professorScoreService
            , IScoreService scoreService
            , IRoleAccessService roleAccessService
            , IUserRoleService userRoleService
            , IProfessorService professorService
            , IIndicatorService indicatorService
            )
        {
            _educationalClassService = educationalClassService;
            _educationalGroupService = educationalGroupService;
            _termService = termService;
            _professorScoreService = professorScoreService;
            _scoreService = scoreService;
            _roleAccessService = roleAccessService;
            _userRoleService = userRoleService;
            _professorService = professorService;
            _indicatorService = indicatorService;
        }

        public ActionResult EducationalClassesManagement()
        {
            SetViewBag("مدیریت جلسات برگزاری کلاس ها", "EducationalClassesManagement");
            Term selectedTerm = null;
            if (string.IsNullOrEmpty(Request.QueryString["termId"]))
                selectedTerm = GetCurrentTerm();
            else
            {
                var termId = Convert.ToInt32(Request.QueryString["termId"]);
                selectedTerm = _termService.Get(g => g.Id == termId);
            }
            var user = (Models.User)Session["UserInfo"];
            var groupQS = 0;
            ViewBag.GroupList = new SelectList(_educationalGroupService.GetMany(w => w.Term.Id == selectedTerm.Id).Where(w => !StaticValue.IneligibleEducationalGroupCodes.Contains((int)w.EducationalGroupCode)), "EducationalGroupCode", "Name");
            ViewBag.TermList = new SelectList(_termService.GetAll().OrderByDescending(o => o.TermCode), "Id", "Name");
            ViewBag.TermId = selectedTerm.Id;
            if (Request.QueryString["group"] != null && int.TryParse(Request.QueryString["group"], out groupQS))
            {
                TempData["model"] = _educationalClassService.GetMany(w => w.Term.Id == selectedTerm.Id && w.EducationalGroup.EducationalGroupCode == groupQS).ToList();
                TempData["groupId"] = groupQS;
            }
            if ((user == null || user.EducationalGroupCode == null) && TempData["model"] == null)
                return View();
            if (TempData["model"] != null)
            {
                var classes = (List<Model.Models.EducationalClass>)TempData["model"];
                ViewBag.GroupId = TempData["groupId"];
                TempData["model"] = null;
                TempData["groupId"] = null;
                return View(classes);
            }
            else
            {
                var groupId = _educationalGroupService.Get(x => x.EducationalGroupCode == user.EducationalGroupCode && x.Term.Id == selectedTerm.Id).Id;
                var classes = _educationalGroupService.Get(g => g.Id == groupId).EducationalClasses.Where(w => w.Term.Id == selectedTerm.Id).ToList();
                return View(classes);
            }

        }

        //public ActionResult EducationalClassesManagementForAdmin(string group)
        //{
        //    var term = GetCurrentTerm();
        //    var groupId = Convert.ToInt32(group);
        //    var classes = _educationalGroupService.Get(g => g.Id == groupId).EducationalClasses.Where(w => w.Term.Id == term.Id).ToList();
        //    TempData["model"] = classes;
        //    TempData["groupId"] = groupId;
        //    return this.Json(string.Empty);
        //}

        public ActionResult EditClassDetails()
        {
            ViewBag.TermId = Request.QueryString["termId"];
            var cid = Convert.ToInt32(Request.QueryString["class"]);
            return PartialView(_educationalClassService.Get(g => g.CodeClass == cid));
        }
        public ActionResult UpdateClassInfoFromExcel()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult UploadAndUpdateClassInfo(string groupId, string termId)
        {
            var rowCount = 0;
            var tid = Convert.ToInt32(termId);
            var badRows = new List<int>();
            foreach (string file in Request.Files)
            {
                var fileContent = Request.Files[file];
                if (fileContent != null && fileContent.ContentLength > 0)
                {
                    var stream = fileContent.InputStream;
                    var ext = fileContent.FileName.Substring(fileContent.FileName.LastIndexOf('.'));
                    var fileName = DateTime.Now.ToString("yyyyMMddHHmmssffff") + ext;
                    var folderPath = Server.MapPath("~/Content/userUploads");
                    if (!Directory.Exists(folderPath))
                        Directory.CreateDirectory(folderPath);
                    var path = Path.Combine(folderPath, fileName);
                    using (var fileStream = System.IO.File.Create(path))
                    {
                        stream.Seek(0, SeekOrigin.Begin);
                        stream.CopyTo(fileStream);
                    }

                    string con = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + path + ";Extended Properties=Excel 12.0;";
                    using (OleDbConnection connection = new OleDbConnection(con))
                    {
                        connection.Open();
                        OleDbCommand command = new OleDbCommand("select * from [Sheet1$]", connection);
                        using (OleDbDataReader dr = command.ExecuteReader())
                        {

                            do
                            {
                                rowCount++;
                                var classCode = 0;
                                var onlineHeld = -1;
                                var offlineHeld = -1;
                                var otherHeld = -1;

                                if (rowCount != 1 && int.TryParse(dr[0].ToString(), out classCode) && classCode > 0
                                        && (string.IsNullOrEmpty(dr[1].ToString()) || (!string.IsNullOrEmpty(dr[1].ToString()) && int.TryParse(dr[1].ToString(), out onlineHeld) && onlineHeld > 0))
                                        && (string.IsNullOrEmpty(dr[2].ToString()) || (!string.IsNullOrEmpty(dr[2].ToString()) && int.TryParse(dr[2].ToString(), out offlineHeld) && offlineHeld > 0))
                                        && (string.IsNullOrEmpty(dr[3].ToString()) || (!string.IsNullOrEmpty(dr[3].ToString()) && int.TryParse(dr[3].ToString(), out otherHeld) && otherHeld > 0))
                                    )
                                {
                                    var classObj = _educationalClassService.Get(g => g.CodeClass == classCode && g.Term.Id == tid);
                                    var gid = Convert.ToInt32(groupId);
                                    if (classObj != null && classObj.EducationalGroup.EducationalGroupCode == gid)
                                        UpdateClassSessions(classCode, onlineHeld, offlineHeld, otherHeld, termId, false);
                                    else
                                        badRows.Add(rowCount);
                                }
                                else if (rowCount != 1)
                                    badRows.Add(rowCount);
                            }
                            while (dr.Read());

                        }
                    }
                    System.IO.File.Delete(path);
                }
            }
            dynamic res = new ExpandoObject();
            res.TotalCount = rowCount - 1;
            res.ErrorCount = badRows.Count();
            res.BadRows = String.Join(", ", badRows.ToArray()); ;
            res.Added = rowCount - badRows.Count() - 1;
            return Content(JsonConvert.SerializeObject(res), "application/json");
        }

        [HttpPost]
        public ActionResult UpdateClassDetails(string classCodeData, string onlineHeld, string presentHeld, string other, string termId)
        {
            var classCode = 0;
            var onlineSessions = 0;
            var offlineSessions = 0;
            var otherSessions = 0;
            int.TryParse(onlineHeld, out onlineSessions);
            int.TryParse(presentHeld, out offlineSessions);
            int.TryParse(other, out otherSessions);
            if (int.TryParse(classCodeData, out classCode) && classCode > 0)
                UpdateClassSessions(classCode, onlineSessions, offlineSessions, otherSessions, termId, true);
            return null;
        }

        public void UpdateClassSessions(int classCode, int onlineHeld, int presentHeld, int other, string termId = null, bool manualUpdate = false)
        {

IAUECProfessorsEvaluation.Web/Views/EducationalClasses/EditClassDetails.cshtml
@{Layout = "~/Views/Shared/_BlankLayout.cshtml";}
@model IAUECProfessorsEvaluation.Model.Models.EducationalClass

<style>
    .educationalClassInfo .row{margin-bottom: 15px;}
</style>

<div class="educationalClassInfo">
    <div class="row">
        <div class="col-sm-2">
            کد کلاس:
        </div>
        <div class="col-sm-3">
            @Model.CodeClass
        </div>
        <div class="col-sm-4">
            تعداد جلسات برگزار شده بصورت آنلاین:
        </div>
        <div class="col-sm-3">
            @Html.TextBoxFor(t => t.OnlineHeldingCount, new { @class = "form-control", @id = "onlineHelding" })
        </div>
    </div>
    <div class="row">
        <div class="col-sm-2">
            عنوان کلاس:
        </div>
        <div class="col-sm-3">
            @Model.Name
        </div>
        <div class="col-sm-4">
            تعداد جلسات برگزار شده بصورت حضوری:
        </div>
        <div class="col-sm-3">
            @Html.TextBoxFor(t => t.PersentHeldingCount, new { @class = "form-control", @id = "persentHelding" })
        </div>
        

    </div>
    <div class="row">
        <div class="col-sm-2">
            نام استاد:
        </div>
        <div class="col-sm-3">
            @Model.Professor.Name @Model.Professor.Family
        </div>
        <div class="col-sm-4">
            سایر جلسات (تعطیلات رسمی، لغو شده و ...):
        </div>
        <div class="col-sm-3">
            @Html.TextBoxFor(t => t.OthersHeldingCount, new { @class = "form-control", @id = "othersHelding" })
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 textCenter">
            <a href="/" class="btn btn-success" id="btnSave">ذخیره</a>
        </div>
    </div>
</div>

<script>
    $(function () {
        $(document).on('click', '#btnSave', function (e) {
            e.preventDefault();
            $.ajax({
                url: '/EducationalClasses/UpdateClassDetails',
                type: 'POST',
                data: {
                    classCodeData: @Model.CodeClass,
                    onlineHeld: $('#onlineHelding').val(),
                    presentHeld: $('#persentHelding').val(),
                    other: $('#othersHelding').val(),
                    termId: @ViewBag.TermId
                },
                success: function (result) {
                    //$('.ui-dialog-content').dialog('close');
                    location.reload();
                }
            });
        });
    });
</script>

IAUECProfessorsEvaluation.Web/Views/EducationalClasses/EducationalClassesManagement.cshtml
@{Layout = "~/Views/Shared/_Layout.cshtml";}
@model List<IAUECProfessorsEvaluation.Model.Models.EducationalClass>
@using GridMvc.Html
@{
    var canChangeGroup = Session["UserInfo"] != null
        && (((IAUECProfessorsEvaluation.Web.Models.User)Session["UserInfo"]).IsAdministrator || ((IAUECProfessorsEvaluation.Web.Models.User)Session["UserInfo"]).IsPowerUser);
}

<style>
    .searchRow {
        border-bottom: 1px solid #ccc;
        background: #ddd;
        margin-left: -20px;
        margin-right: -20px;
        height: 50px;
    }

        .searchRow .form-group {
            margin-bottom: 0;
            margin-top: 8px;
        }

        .searchRow .control-label {
            line-height: 36px;
            font-size: 16px;
        }

    .marginTop {
        margin-top: 75px;
    }

    .topPanel {
        margin-top: 10px;
    }
</style>


<div class="row searchRow">
    <div class="col-sm-12">
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <span class="control-label">ترم: </span>
                </div>
                <div class="col-sm-3">
                    @Html.DropDownList("TermList", (SelectList)ViewBag.TermList, "انتخاب کنید", new { @class = "form-control termList" })
                </div>
                @if (canChangeGroup)
                {
                    <div class="col-sm-1">
                        <span class="control-label">نام گروه: </span>
                    </div>
                    <div class="col-sm-3">
                        @Html.DropDownList("GroupList", (SelectList)ViewBag.CollegeList, "انتخاب کنید", new { @class = "form-control groupList" })
                    </div>
                }
                <div class="col-sm-2">
                    <a href="/" id="btnSelectGroup" class="btn btn-info">انتخاب</a>
                </div>
            </div>
        </div>
    </div>
</div>


@if (Model != null)
{
    <div class="row topPanel">
        <div class="col-sm-12">
            <a href="#" class="btn btn-info" id="btnUploadExcelWindow">
                <i class="fa fa-plus"></i> <span>بارگذاری اطلاعات بصورت گروهی</span>
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            @Html.Grid(Model).Columns(columns =>
   {
       columns.Add(model => model.CodeClass).Titled("کد کلاس").SetWidth("10%").Filterable(true).Sortable(true);
       columns.Add(model => model.Name).Titled("عنوان کلاس").SetWidth("25%").Filterable(true).Sortable(true);
       columns.Add(model => model.Professor.Name).RenderValueAs(o => o.Professor.Name + " " + o.Professor.Family).Titled("نام استاد").SetWidth("25%").Filterable(true).Sortable(true);

       columns.Add(model => model.OnlineHeldingCount).Titled("تعداد جلسات برگزار شده آنلاین").SetWidth("10%").Filterable(true).Sortable(true);
       columns.Add(model => model.PersentHeldingCount).Titled("تعداد جلسات برگزار شده حضوری").SetWidth("10%").Filterable(true).Sortable(true);
       columns.Add(model => model.OthersHeldingCount).Titled("تعداد سایر جلسات (تعطیلات رسمی و ...)").SetWidth("10%").Filterable(true).Sortable(true);

       columns.Add(model => model.Id).Titled("عملیات").SetWidth("10%").Filterable(false)
       .Encoded(false).Sanitized(false)
       .RenderValueAs(o => "<a id=\"EditClassDetails\" href=\"/\" class=\"btn btn-info\" data-id=\"" + o.CodeClass + "\"><i class=\"fa fa-info\"></i> ویرایش</a>");
   }).WithMultipleFilters().WithPaging(20).EmptyText("موردی جهت نمایش یافت نشد.").SetLanguage("fa")
        </div>
        <div id="dialog"></div>
    </div>
}
else if (((IAUECProfessorsEvaluation.Web.Models.User)Session["UserInfo"]) != null && !(((IAUECProfessorsEvaluation.Web.Models.User)Session["UserInfo"]).IsAdministrator || ((IAUECProfessorsEvaluation.Web.Models.User)Session["UserInfo"]).IsPowerUser))
{
    <div class="alert alert-danger marginTop">
        <span>گروهی برای شما تعیین نشده است.</span>
    </div>
}

<script>
    $(function () {
        $(document).on('click', '#btnSelectGroup', function (e) {
            e.preventDefault();
            @if (canChangeGroup)
            {
                <text>
            if ($('#GroupList').val() !== '' && $('#TermList').val() !== '') {
                $('.loadingWrapper').show();
                window.location.href = "/EducationalClasses/EducationalClassesManagement/?group=" + $('#GroupList').val() + "&termId=" + $('#TermList').val();
            }
            </text>
            }
            else
            {
                <text>
            if($('#TermList').val() !== ''){
                $('.loadingWrapper').show();
                window.location.href = "/EducationalClasses/EducationalClassesManagement/?termId=" + $('#TermList').val();
            }
            </text>
            }



            @*$.ajax({
                url: '@Url.Action("EducationalClassesManagementForAdmin", "EducationalClasses")',
                type: 'POST',
                data: { 'group': $('#GroupList').val() },
                success: function (data) {
                    window.location.href = "/EducationalClasses/EducationalClassesManagement"
                }
            });*@
        });
        @if(Model != null)
        {
            <text>
        $('#GroupList').val(@ViewBag.GroupId);
        $('#TermList').val(@ViewBag.TermId);
        </text>
        }


        $(document).on('click', '#EditClassDetails', function (e) {
            e.preventDefault();
            @if (!string.IsNullOrEmpty(Request.QueryString["termId"]))
            {
                <text>

            var href = "/EducationalClasses/EditClassDetails/?class=" + $(this).data("id") + "&termId=" + @Request.QueryString["termId"];
            $('#dialog').dialog({
                modal: true,
                open: function (event, ui) {
                    $(this).load(href, function (result) { });
                    return false;
                },
                width: 768,
                maxHeight: 600,
                minHeight: 300,
                close: function (event, ui) { $('#dialog').html("") }
            });
            </text>
        }
            return false;
        });

        $(document).on('click', '#btnUploadExcelWindow', function (e) {
            e.preventDefault();
            @if (!string.IsNullOrEmpty(Request.QueryString["group"])) {
                    <text>
            var href = "/EducationalClasses/UpdateClassInfoFromExcel/?group=" + @Request.QueryString["group"] + "&termId=" + @Request.QueryString["termId"];
            $('#dialog').dialog({
                modal: true,
                open: function (event, ui) {
                    $(this).load(href, function (result) { });
                    return false;
                },
                width: 768,
                maxHeight: 300,
                minHeight: 100,
                close: function (event, ui) { $('#dialog').html(""); location.reload(); }
            });
            </text>
    }
            return false;
        });

        $('.termList').on('change', function () {
            $('.groupList').html('<option>انتخاب کنید</option>');
            if ($('.termList').val() != '') {
                $('.loadingWrapper').show();
                $.ajax({
                    url: '@Url.Action("GetGroupsByTermId", "Professor")',
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    method: 'GET',
                    data: { termId: $('.termList').val() },
                    success: function (e) {
                        if (e != null) {
                            $.each(e, function (i, v) {
                                $('.groupList').append('<option value="' + v.EducationalGroupCode + '">' + v.Name +'</option>')
                            });
                        }
                        $('.loadingWrapper').hide();
                    }
                });
            }
        });
    });
</script>

IAUECProfessorsEvaluation.Web/Views/EducationalClasses/UpdateClassInfoFromExcel.cshtml
@{Layout = "~/Views/Shared/_BlankLayout.cshtml";}

<style>
    .ui-widget-content a {
        color: #fff;
    }

    .btn-file {
        position: relative;
        overflow: hidden;
    }

        .btn-file input[type=file] {
            position: absolute;
            top: 0;
            right: 0;
            min-width: 100%;
            min-height: 100%;
            font-size: 100px;
            text-align: right;
            filter: alpha(opacity=0);
            opacity: 0;
            outline: none;
            background: white;
            cursor: inherit;
            display: block;
        }
</style>

<div class="row" id="resultBox">
    <div id="resultContent"></div>
</div>
<div class="row">
    <div class="col-sm-6">
        <a href="~/Content/files/اطلاعات کلاس ها.xlsx" class="btn btn-info form-control">
            <i class="fa fa-download"></i> <span>دانلود فرمت فایل اکسل</span>
        </a>
    </div>
    <div class="col-sm-6">
        @*<input type="file" class="custom-file-input" />*@
        <span class="btn btn-primary btn-file">
            انتخاب فایل <input type="file" id="file" accept=".xls,.xlsx, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel">
        </span>
        <a href="#" class="btn btn-success disabled" id="btnUpload">
            <i class="fa fa-upload"></i> <span>بارگذاری</span>
        </a>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        $('#resultBox').hide();

        $(document).on('change', ':file', function () {
            var input = $(this), numFiles = input.get(0).files ? input.get(0).files.length : 1, label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
            if (numFiles == 1)
                $('#btnUpload').removeClass('disabled');
        });

        $('#btnUpload').click(function (e) {
            e.preventDefault();
            var formData = new FormData();
            formData.append('file', $('#file')[0].files[0]);
            $('.loadingWrapper').show();
            $.ajax({
                url: '/EducationalClasses/UploadAndUpdateClassInfo/?groupId=' + @Request.QueryString["group"] + "&termId=" + @Request.QueryString["termId"],
                type: 'POST',
                data: formData,
                processData: false,
                contentType: false,
                success: function (result) {
                    var errorCount = parseInt(result.ErrorCount);
                    var totalCount = parseInt(result.TotalCount);
                    var addedCount = parseInt(result.Added);
                    var resHtml = '<ul>';
                    resHtml += '<li>تعداد کل داده ها: ' + result.TotalCount + '</li>';
                    resHtml += '<li>تعداد داده های بروزرسانی شده: ' + result.Added + '</li>';
                    if(errorCount > 0)
                        resHtml += '<li>ردیف های دارای خطا: ' + result.BadRows + '</li>';
                    resHtml += '</ul>';
                    var alertClass = 'col-sm-12 alert ';
                    if(errorCount == 0)
                        alertClass += 'alert-success';
                    else if(addedCount > 0)
                        alertClass += 'alert-warning';
                    else
                        alertClass += 'alert-danger';
                    $('#resultContent').attr('class', alertClass);
                    $('#resultContent').html(resHtml);
                    $('#resultBox').show();
                    $('.loadingWrapper').hide();
                }
            });
        });
    });
</script>